name = "pdg-t3st-redirector"
type = "javascript"
account_id = "257d9994d1e15e8fbeb6053f590ad96b"
workers_dev = false
route = "t3st.games/l/*"
zone_id = "32e2f76c4ca51f635922c3ca9726083b"
kv_namespaces = [
  { binding = "LINKS", id = "a08d8f58b1124e45891c64b39fbebdb5" }
]
